### ISSUE TITLE
strtime.py: Add second handling

### ISSUE THREAD

**Issue by jkazimierczak** [jkazimierczak/wicamp#1]
Seconds are not handled properly. Traceback:
```
Traceback (most recent call last):
  File "/home/jkazimierczak/wicamp/main.py", line 49, in <module>
    main()
  File "/home/jkazimierczak/wicamp/main.py", line 44, in main
    app.wander(item, datetime.timedelta(minutes=minutes))
  File "/home/jkazimierczak/wicamp/wicamp/app.py", line 129, in wander
    print(f"diff={strtime_diff(initial_reported_time, reported_time)}min (start: {initial_reported_time} | now: {reported_time})")
  File "/home/jkazimierczak/wicamp/wicamp/strtime.py", line 13, in strtime_diff
    return abs(to_minutes(time1) - to_minutes(time2))
  File "/home/jkazimierczak/wicamp/wicamp/strtime.py", line 4, in to_minutes
    return int(parts[0].strip("min"))
ValueError: invalid literal for int() with base 10: '10s'
```

**Comment by jkazimierczak** [comment]
Time is displayed in either seconds, minutes or hours+minutes.
