### ISSUE TITLE
Queried string not found

### ISSUE THREAD

**Issue by jkazimierczak** [jkazimierczak/wicamp#5]
In rare cases this error can be encountered:
```
Queried string ("Wykład 14: Współbieżność i synchronizacja procesów, systemowe mechanizmy synchronizacji") not found.
Traceback (most recent call last):
  File "F:\Projects\Python\wicamp\main.py", line 48, in <module>
    main()
  File "F:\Projects\Python\wicamp\main.py", line 43, in main
    app.wander(item, datetime.timedelta(minutes=minutes))
  File "F:\Projects\Python\wicamp\wicamp\app.py", line 147, in wander
    self.console.print(Text.assemble(f"Obecny czas w tej aktyności: ", (initial_reported_time, "bold")))
  File "C:\Users\kuba\AppData\Local\pypoetry\Cache\virtualenvs\wicamp-Cr1R91Co-py3.10\lib\site-packages\rich\text.py", line 381, in assemble
    append(*part)
  File "C:\Users\kuba\AppData\Local\pypoetry\Cache\virtualenvs\wicamp-Cr1R91Co-py3.10\lib\site-packages\rich\text.py", line 905, in append
    raise TypeError("Only str or Text can be appended to Text")
TypeError: Only str or Text can be appended to Text
```

**Comment by jkazimierczak** [comment]
Same happens with `Wykład 10: Zarządzanie pamięcią ulotną w systemie operacyjnym`. This still needs investigation.
